// Generated by scripts/generate-book.mjs. Do not edit manually.

export interface BookProgressSection {
  readonly slug: string;
  readonly title: string;
  readonly href: string;
}

export interface LearningPath {
  readonly id: string;
  readonly title: string;
  readonly purpose: string;
  readonly estimatedScope: string;
  readonly sectionSlugs: readonly string[];
}

export const bookProgressSections = [
  {"slug":"introduction","title":"System Design Checklist Book","href":"/"},
  {"slug":"book-plan","title":"Book plan","href":"/book/book-plan"},
  {"slug":"what-we-adopted-from-hellointerview","title":"What we adopted from HelloInterview","href":"/book/what-we-adopted-from-hellointerview"},
  {"slug":"practical-system-design-workflow","title":"Practical system-design workflow","href":"/book/practical-system-design-workflow"},
  {"slug":"the-12-question-system-design-loop","title":"The 12-question system design loop","href":"/book/the-12-question-system-design-loop"},
  {"slug":"1-requirements-frs-nfrs-constraints-and-assumptions","title":"1. Requirements: FRs, NFRs, Constraints, and Assumptions","href":"/book/1-requirements-frs-nfrs-constraints-and-assumptions"},
  {"slug":"2-boundaries-state-and-data","title":"2. Boundaries, State, and Data","href":"/book/2-boundaries-state-and-data"},
  {"slug":"2a-networking-and-communication","title":"2A. Networking and Communication","href":"/book/2a-networking-and-communication"},
  {"slug":"2b-data-modeling-indexing-and-partitioning","title":"2B. Data Modeling, Indexing, and Partitioning","href":"/book/2b-data-modeling-indexing-and-partitioning"},
  {"slug":"2c-time-clocks-and-ordering","title":"2C. Time, Clocks, and Ordering","href":"/book/2c-time-clocks-and-ordering"},
  {"slug":"3-concurrency","title":"3. Concurrency","href":"/book/3-concurrency"},
  {"slug":"4-transactions-and-consistency","title":"4. Transactions and Consistency","href":"/book/4-transactions-and-consistency"},
  {"slug":"5-apis-contracts-and-idempotency","title":"5. APIs, Contracts, and Idempotency","href":"/book/5-apis-contracts-and-idempotency"},
  {"slug":"6-messaging-and-asynchronous-work","title":"6. Messaging and Asynchronous Work","href":"/book/6-messaging-and-asynchronous-work"},
  {"slug":"6a-real-time-and-long-running-work","title":"6A. Real-Time and Long-Running Work","href":"/book/6a-real-time-and-long-running-work"},
  {"slug":"7-failure-handling-and-resilience","title":"7. Failure Handling and Resilience","href":"/book/7-failure-handling-and-resilience"},
  {"slug":"8-scale-capacity-performance-and-caching","title":"8. Scale, Capacity, Performance, and Caching","href":"/book/8-scale-capacity-performance-and-caching"},
  {"slug":"9-security","title":"9. Security","href":"/book/9-security"},
  {"slug":"10-observability-and-reliability","title":"10. Observability and Reliability","href":"/book/10-observability-and-reliability"},
  {"slug":"11-deployment-migration-and-evolution","title":"11. Deployment, Migration, and Evolution","href":"/book/11-deployment-migration-and-evolution"},
  {"slug":"12-cost-simplicity-and-operability","title":"12. Cost, Simplicity, and Operability","href":"/book/12-cost-simplicity-and-operability"},
  {"slug":"13-master-system-design-review-checklist","title":"13. Master System Design Review Checklist","href":"/book/13-master-system-design-review-checklist"},
  {"slug":"14-requirements-to-delivery-lifecycle-fr-nfr-constraints-adr-and-tip","title":"14. Requirements-to-Delivery Lifecycle: FR, NFR, Constraints, ADR, and TIP","href":"/book/14-requirements-to-delivery-lifecycle-fr-nfr-constraints-adr-and-tip"},
  {"slug":"15-llm-and-agentic-systems","title":"15. LLM and Agentic Systems","href":"/book/15-llm-and-agentic-systems"},
  {"slug":"16-spec-driven-development-for-agentic-systems","title":"16. Spec-Driven Development for Agentic Systems","href":"/book/16-spec-driven-development-for-agentic-systems"},
  {"slug":"17-agent-system-design-review-checklist","title":"17. Agent-System Design Review Checklist","href":"/book/17-agent-system-design-review-checklist"},
  {"slug":"architecture-decision-record-short-template","title":"Architecture Decision Record — short template","href":"/book/architecture-decision-record-short-template"},
  {"slug":"design-review-outcome-template","title":"Design review outcome template","href":"/book/design-review-outcome-template"},
  {"slug":"compact-glossary","title":"Compact glossary","href":"/book/compact-glossary"},
  {"slug":"about-the-diagrams","title":"About the diagrams","href":"/book/about-the-diagrams"},
  {"slug":"references-and-verification-register","title":"References and verification register","href":"/book/references-and-verification-register"}
] as const satisfies readonly BookProgressSection[];

export const learningPaths = [
  {"id":"interview-preparation","title":"Interview preparation","purpose":"Practice a repeatable design flow and the trade-offs most often explored in interviews.","estimatedScope":"12 sections · 3–5 hours","sectionSlugs":["practical-system-design-workflow","the-12-question-system-design-loop","1-requirements-frs-nfrs-constraints-and-assumptions","2b-data-modeling-indexing-and-partitioning","3-concurrency","4-transactions-and-consistency","5-apis-contracts-and-idempotency","6-messaging-and-asynchronous-work","7-failure-handling-and-resilience","8-scale-capacity-performance-and-caching","13-master-system-design-review-checklist","design-review-outcome-template"]},
  {"id":"architecture-review","title":"Architecture review","purpose":"Review an architecture systematically from boundaries through operability and evolution.","estimatedScope":"17 sections · 5–7 hours","sectionSlugs":["1-requirements-frs-nfrs-constraints-and-assumptions","2-boundaries-state-and-data","2a-networking-and-communication","2b-data-modeling-indexing-and-partitioning","2c-time-clocks-and-ordering","4-transactions-and-consistency","5-apis-contracts-and-idempotency","6-messaging-and-asynchronous-work","7-failure-handling-and-resilience","8-scale-capacity-performance-and-caching","9-security","10-observability-and-reliability","11-deployment-migration-and-evolution","12-cost-simplicity-and-operability","13-master-system-design-review-checklist","architecture-decision-record-short-template","design-review-outcome-template"]},
  {"id":"agentic-systems","title":"Agentic systems","purpose":"Design agent and LLM systems with explicit contracts, failure boundaries, and review gates.","estimatedScope":"9 sections · 3–4 hours","sectionSlugs":["1-requirements-frs-nfrs-constraints-and-assumptions","5-apis-contracts-and-idempotency","6-messaging-and-asynchronous-work","7-failure-handling-and-resilience","9-security","10-observability-and-reliability","15-llm-and-agentic-systems","16-spec-driven-development-for-agentic-systems","17-agent-system-design-review-checklist"]}
] as const satisfies readonly LearningPath[];
