import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const sourcePath = path.join(projectRoot, "docs", "System_Design_Checklist_Book.md");
const targetPath = path.join(projectRoot, "app", "book-content.generated.ts");

function sectionSlug(title, index) {
  if (index === 0) return "introduction";
  return title
    .toLowerCase()
    .replace(/[—–]/g, "-")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 72);
}

function sectionSummary(markdown) {
  const paragraph = markdown
    .split(/\n\s*\n/)
    .map((value) => value.replace(/^>\s?/gm, "").trim())
    .find((value) => value && !value.startsWith("#") && !value.startsWith("|") && !value.startsWith("```"));
  return (paragraph ?? "Open this section of the complete handbook.").replace(/[*_`]/g, " ").slice(0, 240);
}

function parseSections(source) {
  const matches = [...source.matchAll(/^# (.+)$/gm)];
  return matches.map((match, index) => {
    const start = (match.index ?? 0) + match[0].length;
    const end = matches[index + 1]?.index ?? source.length;
    const markdown = source.slice(start, end).trim();
    return {
      slug: sectionSlug(match[1], index),
      number: String(index + 1).padStart(2, "0"),
      title: match[1].trim(),
      summary: sectionSummary(markdown),
      markdown,
    };
  });
}

function generatedModule(sections) {
  return `// Generated by scripts/generate-book.mjs. Do not edit manually.\n\nexport interface BookSection {\n  readonly slug: string;\n  readonly number: string;\n  readonly title: string;\n  readonly summary: string;\n  readonly markdown: string;\n}\n\nexport const bookSections = ${JSON.stringify(sections, null, 2)} as const satisfies readonly BookSection[];\n\nexport function findBookSection(slug: string) {\n  return bookSections.find((section) => section.slug === slug);\n}\n\nexport const bookSiteMap = bookSections.map((section) => \`${"${section.number}"} ${"${section.title}"} (/book/${"${section.slug}"})\`).join(\"\\n\");\n`;
}

const sections = parseSections(fs.readFileSync(sourcePath, "utf8"));
fs.writeFileSync(targetPath, generatedModule(sections));
console.log(`Generated ${sections.length} book sections.`);
